### ISSUE TITLE
Does it really require Julia v1.5 to install?

### ISSUE THREAD

**Issue by singularitti** [thchr/Brillouin.jl#11] opened 2021-08-17 06:57 UTC
It seems like this package requires Julia v1.5 and above, is it necessary? Can we relax the version in Project.toml to v1.0?

**Comment by thchr** [comment] 2021-08-17 11:06
Hmm, it might work on earlier versions 🤷? The problem is that I haven't actively tried to keep any compatibility with older Julia versions - and don't particularly want to do that going forward either; it a hassle - so I don't know if the 1.5 bound is in fact needed.

If you have a use case, I could definitely lower the compat bound but would probably still only have time to maintain stability on more recent Julia versions going forward.

**Comment by singularitti** [comment] 2021-08-17 18:59
I was trying. But I found it requires Crystalline.jl (which requires Julia v1.4+) so I am updating that one now.

**Comment by thchr** [comment] 2021-08-17 19:01
Brillouin should depend on Crystalline though?

**Comment by singularitti** [comment] 2021-08-17 19:47
> Brillouin should [EDIT: _not_] depend on Crystalline though?

Oh yeah. But I can't run its tests on Julia v1.3.
![image](https://user-images.githubusercontent.com/25192197/129790710-7412197f-76e4-422c-b262-167fc1062a37.png)

**Comment by thchr** [comment] 2021-08-17 19:56
Ah, I see - makes sense... Testing Brillouin pulls in Crystalline to do a few things more simply - but Crystalline definitely depends on Julia being v1.3+ (probably, it even depends on v1.4+ honestly).

**Comment by thchr** [comment] 2021-08-17 19:56
So that's a bit of a show-stopper for testing Brillouin on earlier versions of Julia certainly...

**Comment by thchr** [comment] 2021-12-14 23:16
I think it'll be fine to close this issue now, given that Julia v1.6 is the new LTS.
I'll probably bump the Julia version bound to v1.6 for Brillouin at some point.

**Closed by thchr** 2021-12-14 23:16 UTC
