### ISSUE TITLE
Illegal instruction error

### ISSUE THREAD

**Issue by gkemlin** [thchr/Brillouin.jl#21] opened 2022-09-21 14:10 UTC
Hi! We are using Brillouin.jl in our code [DFTK.jl](https://github.com/JuliaMolSim/DFTK.jl) and since this morning update we are encountering `Illegal instruction` signals. I can't really manage to reproduce a minimal working example, sorry, but if we downgrade Brillouin.jl to 0.5.8, it works fine.

As far as I know, this should not happen so this might be linked e.g. to the usage of the spglib external library to generate the lattice we use as input to Brillouin.jl ([here](https://github.com/JuliaMolSim/DFTK.jl/blob/3a720de4d0c19ca25dba2049935dcf568ac221c0/src/postprocess/band_structure.jl#L48)) or something like that, but maybe you already have encountered such errors and have some ideas on where it comes from ?

Thanks in advance :)

**Comment by thchr** [comment] 2022-09-21 14:12
Ugh, that doesn't sound good.

Could you paste the stack trace here?

**Comment by thchr** [comment] 2022-09-21 14:13
I didn't do too many things between 0.5.8 and 0.5.9; most of the things except https://github.com/thchr/Brillouin.jl/commit/bcd79b9dd2be32489ace7e3c99a959e5224966cd and https://github.com/thchr/Brillouin.jl/commit/6cd662d85b73ce11e899faf03d923a6fb952b564 are conditional on having Makie loaded, which I imagine you don't.

**Comment by thchr** [comment] 2022-09-21 14:27
Thanks: unfortunately, I don't understand what is happening here :(
What are the types and values of `sgnum` and `direct_basis`?

**Comment by antoine-levitt** [comment] 2022-09-21 15:23
I've seen this type of weird failures with bad python installs. This looks like a julia bug - I don't think either we (DFT) or you (Brillouin) does anything that could cause this type of issues? What's weird is that it started happening only now - something must have changed somewhere, but what?

**Comment by thchr** [comment] 2022-09-21 16:17
I wonder if this is related to this issue https://github.com/JuliaLang/julia/issues/45704 which seems to implicate a Requires call.

**Comment by gkemlin** [comment] 2022-09-21 19:04
> You say it is fixed on v0.5.8 - is there any particular commit (there's ~5) between v0.5.8 and v0.5.9 (i.e., after [d8179d1](https://github.com/thchr/Brillouin.jl/commit/d8179d1ce64a2a38d3f67a16154fdc837b456a38)) that makes this fail?

Well, from the test I have ran, with `Rs = convert(DirectBasis{D}, Rs)` everything works fine and using `Rs = convert(DirectBasis{D}, Rs)::DirectBasis{D}` from [here](https://github.com/thchr/Brillouin.jl/commit/bcd79b9dd2be32489ace7e3c99a959e5224966cd#diff-8d4364451cd4f8a72d2415d5b94d0522755cc9973b4da22a42e55bd41b71b995R183) raises the Illegal instruction. But again, as Antoine said, it is probably just a coincidence because (i) this should raise an error if there are type issues, not an Illegal instruction and (ii) running locally with the same types as in our code does not raise the Illegal instruction...

**Comment by thchr** [comment] 2022-09-21 19:32
If this is a persistent problem in your CI, I suppose we can just remove that typeassert. I only added it to improve the type-stability of the function for callers that don't supply `Rs` as a `DirectBasis` (e.g., you).

If you can confirm that this fixes it, I'm happy to remove it.

**Comment by mfherbst** [comment] 2022-09-21 22:46
Hmmm this sounds wrong. Why should the type assert be the issue? How reproducible is this? Does anyone get this locally (after deleting the Manifest.toml and updating all packages inside the DFTK project folder).

I'll try to take a look. Might be an issue with spglib or its wrapping?

**Comment by antoine-levitt** [comment] 2022-09-22 07:10
> I only added it to improve the type-stability of the function for callers that don't supply Rs as a DirectBasis (e.g., you).

I don't understand why you'd need the typeassert? Isn't the compiler able to figure out that `convert(T, x)` is of type T?

**Comment by antoine-levitt** [comment] 2022-09-22 07:13
> I wonder if this is related to this issue https://github.com/JuliaLang/julia/issues/45704 which seems to implicate a Requires call.

Interesting. @gkemlin do I understand correctly that you were able to reproduce the crash locally (not in CI)? If so, can you try reproducing it on julia nightly? If the bug persists it would be worth reporting it to the julia repo, this really looks like a julia bug.

**Comment by gkemlin** [comment] 2022-09-22 08:47
> If this is a persistent problem in your CI, I suppose we can just remove that typeassert. I only added it to improve the type-stability of the function for callers that don't supply Rs as a DirectBasis (e.g., you).

I'm not sure this is really the origin of the problem because we do provide Rs as a DirectBasis :sweat_smile: 

> Interesting. @gkemlin do I understand correctly that you were able to reproduce the crash locally (not in CI)? If so, can you try reproducing it on julia nightly? If the bug persists it would be worth reporting it to the julia repo, this really looks like a julia bug.

Yes I reproduced the bug locally. It happened after running DFTK with Julia 1.8 and updating all packages in the Project.toml of the DFKT folder. I'll try deleting the Manifest.toml and running with Julia nightly later today, I'll keep you updated.

**Comment by gkemlin** [comment] 2022-09-22 16:33
Ok, so I've done further testing and I think that it is definitely a Julia bug. The question remains to understand how and why... I have ran the two following tests on my computer with Julia 1.8 after deleting the Manifest.toml from the DFTK.jl folder and the nightly version Julia 1.9.0-DEV.1428, again after deleting the Manifest.toml from the DFTK.jl folder. Both version lead to the same conclusions, which I detail now.

The first test is the one which ends up into the Illegal assertion error. (Sorry, I can't manage to reproduce it without DFTK...). The bug happens when calling this `high_symmetry_kpath` function from DFTK.jl where we use Brillouin.jl functions. Now the fun starts. If I literally just copy-paste the whole code of the `high_symmetry_kpath` function and run it inline, then everything works fine :rofl: 

Those using DFTK, do you end up with the same issue if you delete your Manisfest.toml and repopulate it with latest versions update ?

Test 1
```
using Brillouin
using Bravais
using DFTK
using Plots
using Unitful
using UnitfulAtomic
using StaticArrays

a = 10.26  # Silicon lattice constant in Bohr
lattice = a / 2 * [[0 1 1.];
                   [1 0 1.];
                   [1 1 0.]]
Si = ElementPsp(:Si, psp=load_psp("hgh/lda/Si-q4"))
atoms     = [Si, Si]
positions = [ones(3)/8, -ones(3)/8]

model = model_LDA(lattice, atoms, positions)
kcoords, klabels, kpath = DFTK.high_symmetry_kpath(model; kline_density=40u"bohr")
```

Test 2
```
using Brillouin
using Bravais
using DFTK
using Plots
using Unitful
using UnitfulAtomic
using StaticArrays

a = 10.26  # Silicon lattice constant in Bohr
lattice = a / 2 * [[0 1 1.];
                   [1 0 1.];
                   [1 1 0.]]
Si = ElementPsp(:Si, psp=load_psp("hgh/lda/Si-q4"))
atoms     = [Si, Si]
positions = [ones(3)/8, -ones(3)/8]

model = model_LDA(lattice, atoms, positions)
kline_density = austrip(40u"bohr")

if model.n_dim == 1  # Return fast for 1D model
    # TODO Is this special-casing of 1D is not needed for Brillouin.jl any more
    #
    # Just use irrfbz_path(1, DirectBasis{1}([1.0]))
    # (see https://github.com/JuliaMolSim/DFTK.jl/pull/496/files#r725205860)
    #
    # Length of the kpath is recip_lattice[1, 1] in 1D
    n_points = max(2, 1 + ceil(Int, kline_density * model.recip_lattice[1, 1]))
    kcoords  = [@SVector[coord, 0, 0] for coord in range(-1//2, 1//2, length=n_points)]
    klabels  = Dict("Γ" => zeros(3), "-½" => [-0.5, 0.0, 0.0], "½" => [0.5, 0, 0])
    return (kcoords=kcoords, klabels=klabels,
            kpath=[["-½", "½"]], kbranches=[1:length(kcoords)])
end

# - Brillouin.jl expects the input direct lattice to be in the conventional lattice
#   in the convention of the International Table of Crystallography Vol A (ITA).
# - spglib uses this convention for the returned conventional lattice,
#   so it can be directly used as input to Brillouin.jl
# - The output k-Points and reciprocal lattices will be in the CDML convention.
conv_latt = DFTK.spglib_standardize_cell(model; primitive=false,correct_symmetry=false).lattice
sgnum     = DFTK.spglib_spacegroup_number(model)  # Get ITA space-group number
direct_basis   = Bravais.DirectBasis(collect(eachcol(conv_latt)))
primitive_latt = Bravais.primitivize(direct_basis, Bravais.centering(sgnum, 3))

primitive_latt ≈ collect(eachcol(model.lattice)) || @warn(
    "DFTK's model.lattice and Brillouin's primitive lattice do not agree. " *
    "The kpath selected to plot the band structure might not be most appropriate."
)

kp     = Brillouin.irrfbz_path(sgnum, direct_basis)
kinter = Brillouin.interpolate(kp, density=kline_density)

# TODO Need to take care of time-reversal symmetry here!
#      See https://github.com/JuliaMolSim/DFTK.jl/pull/496/files#r725203554

# Need to double the points whenever a new path starts
# (for temporary compatibility with pymatgen)
# TODO Remove this later
kcoords = empty(first(kinter.kpaths))
for kbranch in kinter.kpaths
    idcs = findall(k -> any(sum(abs2, k - kcomp) < 1e-5
                            for kcomp in values(kp.points)), kbranch)
    @assert length(idcs) ≥ 2
    idcs = idcs[2:end-1]  # Don't duplicate first and last
    idcs = sort(append!(idcs, 1:length(kbranch)))
    append!(kcoords, kbranch[idcs])
end

T = eltype(kcoords[1])
klabels = Dict{String,Vector{T}}(string(key) => val for (key, val) in kp.points)
kpath   = [[string(el) for el in path] for path in kp.paths]
(; kcoords, klabels, kpath)
```

**Comment by antoine-levitt** [comment] 2022-09-23 06:16
OK, there is no native code involved so I'd think it's clearly a julia bug. Can you post it on the julia issue tracker, with the instructions to reproduce?

**Comment by mfherbst** [comment] 2022-09-27 14:29
This is now fixed on the Julia side, but of course we are still suffering from it in the released versions for a while, which is a bit annoying for people picking up Julia for the first time to try DFTK. 

@thchr Would you mind removing the type assert until the fixed Julia versions are more wide-spread? I don't like this idea very much, but I can't think of a better "solution" right now.

**Comment by thchr** [comment] 2022-09-27 14:32
I don't mind, yeah - I've been thinking the same thing needs to be done.

I'll initially just wrap this in a `VERSION` check, and then later on, I may remove that check, restoring the typeassert, and then simply bound the Project.toml Julia version to something where it is fixed (i.e., then Brillouin will just be downloaded at a fixed "old" version later on).

**Closed** 2022-09-27 14:55 UTC

**Comment by thchr** [comment] 2022-09-27 14:57
I've fixed it in https://github.com/thchr/Brillouin.jl/commit/7be63e036d28aa789328bf71d31da74a12599dbe and registered a new version (v0.5.10): should be in the Registry in ~15 min or so.

**Comment by antoine-levitt** [comment] 2022-09-27 15:22
Hm interesting. I don't understand this at all - surely there are no methods that could be called here and would yield a different return type?

**Comment by mfherbst** [comment] 2022-09-27 15:24
Oh yes, for example
```
typeof( convert(AbstractFloat, 1.2) )
```
So basically it is implementation-specific what the return-type of `convert(T, x)` is and it is (in general) not guaranteed to be exactly `T`.

**Comment by antoine-levitt** [comment] 2022-09-27 15:34
Right but here T is a concrete type that is statically known, so if convert(::T, x) is defined then no other method can be possibly called? I guess the convert call can error, but even in that case there's no harm in optimistically infer the return type

**Comment by antoine-levitt** [comment] 2022-09-27 15:39
Eg this works:
```

julia> struct A end

julia> convert(::A, x) = 2
convert (generic function with 1 method)

julia> code_warntype(convert, (A, Any))
MethodInstance for convert(::A, ::Any)
  from convert(::A, x) in Main at REPL[7]:1
Arguments
  #self#::Core.Const(convert)
  _::Core.Const(A())
  x::Any
Body::Int64
1 ─     return 2
```

**Comment by mfherbst** [comment] 2022-09-27 15:46
Yes but in this case this the `convert` function itself is a compile-time constant. Essentially Julia gives you free choice to do anything in `convert` including returning some different object right now. (But it is considered to change this in 2.0, see [Issue 42372](https://github.com/JuliaLang/julia/issues/42372)).

**Comment by antoine-levitt** [comment] 2022-09-27 17:32
What you are talking about is the fact that convert is a mehhod like any other, and everybody is free to define convert(::sometype, x) = 2. This is unrelated to the fact that if f(::some concrete type, x)) = some statically knowable type, the compiler should be able to infer the return value of f(some concrete type, any)?

**Comment by thchr** [comment] 2022-09-27 17:51
I think the issue is the following:
```jl
julia> methods(convert, (Type{DirectBasis{3}}, Any))
# 8 methods for generic function "convert":
[1] convert(::Type{T}, f::LinearAlgebra.Factorization) where T<:AbstractArray in LinearAlgebra at /home/tchr/.julia/juliaup/julia-1.8.1+0.x64/share/julia/stdlib/v1.8/LinearAlgebra/src/factorization.jl:58
[2] convert(::Type{SA}, x::Tuple) where SA<:StaticArraysCore.StaticArray in StaticArrays at /home/tchr/.julia/packages/StaticArrays/atiPw/src/convert.jl:179
[3] convert(::Type{DirectBasis{D}}, vs::StaticArraysCore.StaticArray{Tuple{D}, <:StaticArraysCore.StaticArray{Tuple{D}, <:Real, 1}, 1}) where D in Bravais at /mnt/c/Users/tchr/Dropbox (MIT)/Projects/photonic-topo-sym/julia/Crystalline/Bravais/src/types.jl:29
[4] convert(::Type{SA}, sa::SA) where SA<:StaticArraysCore.StaticArray in StaticArrays at /home/tchr/.julia/packages/StaticArrays/atiPw/src/convert.jl:178
[5] convert(::Type{SA}, sa::StaticArraysCore.StaticArray{S}) where {SA<:StaticArraysCore.StaticArray, S<:Tuple} in StaticArrays at /home/tchr/.julia/packages/StaticArrays/atiPw/src/convert.jl:172
[6] convert(::Type{SA}, a::AbstractArray) where SA<:StaticArraysCore.StaticArray in StaticArrays at /home/tchr/.julia/packages/StaticArrays/atiPw/src/convert.jl:194
[7] convert(::Type{T}, a::T) where T<:AbstractArray in Base at abstractarray.jl:16
[8] convert(::Type{T}, x::T) where T in Base at Base.jl:61
```
Any of these methods is in principle a possible run-time dispatch for callers of `convert` with argument types `Type{DirectBasis{3}}, Any)`. I may misremember, but my understanding is that if there are >4 (roughly) possible matches, inference simply gives up and does not check the return type of each - and simply infers to `Any`. Things may work out if there are fewer matches, but here, there aren't.

**Comment by antoine-levitt** [comment] 2022-09-27 18:17
Ooh, thanks for the explanation, that makes complete sense. Thanks also for the `methods` call, very useful to see what's going on.
